[[main]]
  name = "Docs"
  weight = 1
  url = "/docs/develop/get-started"

[[main]]
  name = "Learn"
  weight = 10
  identifier = "learn"

[[main]]
  parent = "learn"
  name = "About XPLA Chain"
  weight = 11
  url = "/learn/learn/about-xpla-chain"

[[main]]
  parent = "learn"
  name = "Brand Assets"
  weight = 12
  url = "/learn/learn/brand-assets"

[[main]]
  parent = "learn"
  name = "Fees"
  weight = 13
  url = "/learn/learn/fees"

[[main]]
  parent = "learn"
  name = "XPLA Vault"
  weight = 14
  url = "/learn/learn/xpla-vault/contracts"

[[main]]
  parent = "learn"
  name = "Glossary"
  weight = 15
  url = "/learn/learn/glossary"

[[main]]
  name = "Develop"
  weight = 20
  identifier = "develop"

[[main]]
  parent = "develop"
  name = "Get Started"
  weight = 21
  url = "/develop/develop/get-started"

[[main]]
  parent = "develop"
  name = "Guides"
  weight = 22
  url = "/develop/develop/guides/sign-with-a-multisig-account"

[[main]]
  parent = "develop"
  name = "Smart Contract Guide"
  weight = 23
  url = "/develop/develop/smart-contract-guide/overview"

[[main]]
  parent = "develop"
  name = "Tools"
  weight = 24
  url = "/develop/develop/tools/which-tools-to-use"

[[main]]
  parent = "develop"
  name = "Core Modules"
  weight = 25
  url = "/develop/develop/core-modules/overview"

[[main]]
  parent = "develop"
  name = "Dev Reference"
  weight = 25
  url = "/develop/develop/dev-reference/developer-resources"

[[main]]
  name = "Full Node"
  weight = 30
  identifier = "full-node"

[[main]]
  parent = "full-node"
  name = "Run a Full Node"
  weight = 31
  url = "/full-node/full-node/run-a-full-node/overview"

[[main]]
  parent = "full-node"
  name = "Manage a Validator"
  weight = 32
  url = "/full-node/full-node/manage-a-validator/overview"

[[main]]
  parent = "full-node"
  name = "Resources"
  weight = 33
  url = "/full-node/full-node/resources/text-tutorials"

[[social]]
  name = "Twitter"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-twitter\"><path d=\"M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z\"></path></svg>"
  url = "https://twitter.com/xpla_official"
  weight = 10

[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/xpladev/xpla"
  weight = 30

# [[footer]]
#   name = "Privacy"
#   url = "/privacy-policy/"
#   weight = 10
